repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false
      - id: black
        name: black
        entry: black --config ./pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: flake8 --config=pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        types: [ python ]
        pass_filenames: false